### ISSUE TITLE
Bug in Web view with respect to Winter-Time

### ISSUE THREAD

**Issue by henfri** [chriszero/docker-vdr#4]
Hi Chris,

there is a bug in epgds web view with respect to winter-time/day light saving time.
It is fixed in git:
http://www.vdr-portal.de/board16-video-disk-recorder/board55-vdr-plugins/p1281198-epgd-epg2vdr-scraper2vdr/#post1281198

Would you mind updating?

Regards,
Hendrik

**Comment by chriszero** [comment]
Mache ich.

**Comment by chriszero** [comment]
Erledigt.
Es muss auch der "database" Container geupgraded werden.
Dazu muss im laufendem Container ein mysql_upgrade ausgeführt werden.

docker exec database mysql_upgrade --user=root --password=my-secret-pw

**Comment by henfri** [comment]
Thanks, it works!
